[workspace]

resolver = "2"

members = ["katas/simple-platform", "random_plugins/simple-2d-camera"]

[workspace.dependencies]
avian2d = { git = "https://github.com/Jondolf/avian.git", features = ["default"], rev = "52cbcecce0fd05a65005ab6935ebeb231373c2c6" }
bevy = "0.15.0-rc.3"
