[workspace]

resolver = "2"

members = [
    "katas/1-simple-platform",
    "random_plugins/simple-2d-camera",
    "random_plugins/simple-platform-player-controller"
]

[workspace.dependencies]
avian2d = { version = "0.2.0", features = ["default"] }
bevy = "0.15.0"
